services:
  db:
    image: postgres:16.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:6.0.9-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data

volumes:
  db:
  redis:
